### ISSUE TITLE
Yarn or NPM

### ISSUE THREAD

**Issue by MonsieurMan** [orbital-js/orbital#1]
We currently use yarn and npm concurrently we should get rid of this.  

I personnaly prefer using yarn as I find more friendly and find it faster with my slow network.
Also package scripts are already using it.

**Comment by wbhob** [comment]
We can and should use Yarn and NPM

**Comment by MonsieurMan** [comment]
I mean we should not push two differents -lock.json and be inconsistent in scripts. That's what I mean by choosing, just being consistent in what we push to the repo.

**Comment by wbhob** [comment]
let's use NPM, just because it has a larger user base. When we publish, we can generate let yarn pull off of NPM.
