### ISSUE TITLE
[Question] How to remove auto-generated help message

### ISSUE THREAD

**Issue by revant** [orbital-js/orbital#12]
Orbitaljs is awesome! Thanks for sharing it!!

The following message is automatically generated with cli app built with orbital-js

```
This is the auto-generated help for appName
For help understanding these docs, go to https://www.orbital.io/docs/understanding-orbital-documentation.
```

Can it be changed or removed?

**Comment by wbhob** [comment]
there isn’t a setting for this yet, but i’m working on putting together more granular config options. i’ll add this to my list!

**Comment by wbhob** [comment]
Ok, I've added new support for configuration in commit 3e2edb85924e93f61ca29937d202838e22c03933 . It will land in alpha.30 as soon as I write docs for it!

**Comment by wbhob** [comment]
alpha 30 is published
