### ISSUE TITLE
Infer decorated objects name from class name

### ISSUE THREAD

**Issue by MonsieurMan** [orbital-js/orbital#6]
In our example API we've written param usage like so
```ts
// I think we should add the ability to infer name from command and cli modules too
@Command({})
export class GenerateCommand implements Executable {
   execute(
      // Here we would infer name from parameter name
      @Param({}) url: string,
      // Or override it
      @Param({ name: 'uri' }) secondUri: string
   ) { }
}
```
Almost everytime the name you'd give for the cli to display will be the same you use in your code. It should be possible for every of our domain object to have their name inferred from the code, or overriden if you actually specify it. 
That is:
- Cli
- Command
- Param
- Option

**Comment by wbhob** [comment]
Param names effectively don’t matter, because unlike options, they are in a particular order. Also, decorators forbid getting the key of the param.

**Comment by MonsieurMan** [comment]
We need them for automatic help generation.
And here it is from Clime code !
```ts
paramName = paramName ||
   hyphenate(Reflection.getFunctionParameterName(target.execute, index), { lowerCase: true });
```

**Comment by wbhob** [comment]
We can't infer names because that can lead to conflicts. better to be explicit than implicit for commands/cli. Obviously, this has been implemented for params and options!
