### ISSUE TITLE
Automatic help generation and display

### ISSUE THREAD

**Issue by MonsieurMan** [orbital-js/orbital#7]
### Orbital should generate and display automatic help based on
- Cli / Command module
   - Name
   - Brief *(one line description)*
   - Description *(multiline description)*
- Param / Option
   - Name
   - Description   

### How
**An automatic help command added at the root of cli modules**
```sh
orb help [command-names...] [options...]
   aliases: h
Parameters:
   command-names [string] (optionnal) Command path
Options:
   --short [Toggle] Display commands name and briefs only.
   aliases: -s
```

**Default --help option for commands**
```orb new --help```

### Example output
```sh
#orb new --help OR orb help new --help
orb new <name> [optionalParam] [options...]
   Bootstrap a new orbital cli project.
   aliases: orb n
Parameters:
   name [string] The name of the CLI module you want to create.
   optionParam [boolean] (optionnal) An optional parameter
Options:
   --skip-test 
     aliases: -oN -optionName
   --string-option [string] (default: '') An example string option.
```
```sh
# orb help -s
orb new Bootstrap a new orbital cli project.
orb generate Generate and or modify files to manipulate orbital cli object.
orb version Outputs Orbital CLI version.
```
As angular CLI, output should be colorized. *(There is place for improvements)*
>*This could lead to a color theme functionnality*

**Comment by wbhob** [comment]
I've made an initial implementation. Please review?

**Comment by wbhob** [comment]
Have you gotten a chance to test the help gen? I want to close this and move on!

**Comment by wbhob** [comment]
this is done, I'm calling it :)
